import sys, os, os.path

def main():
	repo_dir, repo_url, repo_env = sys.argv[1:]

	repo_dir = repo_dir.rstrip("/")
	repo_url = repo_url.rstrip("/")

	repos = []

	print """# this file is generated by talos: src/wrapper/generate_yum_repo.py
# any local edits will be overwritten the next time talos deploys to this host.
"""

	if repo_env.startswith("local"):
		print "# nothing here, because we're running on a local environment (%s)" % repo_env
		return

	print "# talos environment: %s\n" % repo_env

	if os.path.isdir(os.path.join(repo_dir, 'repodata')):
		repos.append(("talos-"+repo_env, repo_url + "/"))

	for proj in sorted(os.listdir(repo_dir)):
		path = os.path.join(repo_dir, proj)
		if not os.path.isdir(path): continue
		if not os.path.isdir(os.path.join(path, 'repodata')): continue

		repos.append((proj+"-"+repo_env, "%s/%s/" % (repo_url, proj)))

	for proj, url in repos:
		print """[%s]
name=%s repo
baseurl=%s
enabled=1
gpgcheck=0
keepcache=1
""" % (proj, proj, url)

if __name__ == '__main__':
	main()
