---
# Path          : src/playbooks/deploy/roles/haproxy/tasks/main.yml
# Usage         : This role is used to move servers in and out of rotation with haproxy
# Params        : rotation_status

   - name: check if {{ DEPLOY_BASE_DIR }}/conf exists, if not must be a new server or out of rotation
     stat: path={{ DEPLOY_BASE_DIR }}/conf follow=true
     register: conf_status

   - include: set_status.yml
     when: conf_status.stat.isdir is defined and conf_status.stat.isdir == true